query UpcomingEventsQuery {
  labs {
    events(where:{ public:true, state: ACCEPTING_STUDENT_APPLICATIONS }) {
      id
      name
      startsAt
      defaultWeeks
      hasBeginner
      hasIntermediate
      hasAdvanced
    }
  }
}