mutation MentorAddMutation ($data: LabsMentorCreateInput!) {
  labs {
    createMentor(data: $data) {
      id
    }
  }
}

mutation ProjectAddMutation ($mentor: String!, $data: LabsProjectCreateInput!) {
  labs {
    createProject(mentor: { id: $mentor }, data: $data) {
      id
    }
  }
}
