query TopStudentsByTrack ($track: LabsTrack!, $includeRejected: Boolean!) {
  labs {
    statAdmissionsStatus(track: $track) {
      key
      value
    }
    studentsTopRated(track: $track, take: 60, includeRejected: $includeRejected) {
      id
      name
      status
      track
      email
      admissionRatingAverage
      admissionRatingCount
      profile
      partnerCode
      trackRecommendation {
        track
        weight
      }
    }
  }
}

mutation StudentChangeTrack ($id: String!, $track: LabsTrack!) {
  labs {
    editStudent(where: { id: $id }, data: { track: $track }) {
      id
    }
  }
}

mutation StudentTrackChallenge ($id: String!) {
  labs {
    editStudent(where: { id: $id }, data: { status: TRACK_CHALLENGE }) {
      id
    }
  }
}

mutation StudentTrackInterview ($id: String!) {
  labs {
    editStudent(where: { id: $id }, data: { status: TRACK_INTERVIEW }) {
      id
    }
  }
}

mutation StudentReject ($id: String!) {
  labs {
    editStudent(where: { id: $id }, data: { status: REJECTED }) {
      id
    }
  }
}

mutation StudentOfferAdmission ($id: String!) {
  labs {
    offerStudentAdmission(where: { id: $id }) {
      id
    }
  }
}
