query CsvStudents {
  labs {
    students(where: { inStatus: ACCEPTED }, take: 5000) {
      givenName
      surname
      email
      track
      id
    }
    mentors(where: { inStatus: ACCEPTED, withProjects: true }) {
      givenName
      surname
      email
      projects {
        track
      }
      id
    }
  }
}
