mutation SendMentorEmail($where: LabsMentorFilterInput, $subject: String!, $body: String!) {
  labs {
    sendMentorEmail(
      subject: $subject,
      body: $body
      where: $where,
    )
  }
}

mutation SendStudentEmail($where: LabsStudentFilterInput, $subject: String!, $body: String!) {
  labs {
    sendStudentEmail(
      subject: $subject,
      body: $body
      where: $where,
    )
  }
}
