mutation SendMentorEmail($subject: String!, $body: String!) {
  labs {
    sendMentorEmail(
      subject: $subject,
      body: $body
    )
  }
}

mutation SendStudentEmail($subject: String!, $body: String!) {
  labs {
    sendStudentEmail(
      subject: $subject,
      body: $body
    )
  }
}
