#import "../../../../components/Dashboard/MatchBoard.gql"

query LabsMatchBoard {
    labs {
        projects {
            ...ProjectMatch
        }
        students {
            ...StudentMatch
        }
    }
}