query FindByPartnerCode ($code: String!) {
  labs {
    students (where: { partnerCode: $code }) {
      id
      givenName
      surname
      email
      status
      weeks
      track
    }
  }
}

mutation SaveStudentStatus ($id: String!, $status: LabsStudentStatus!) {
  labs {
    editStudent(where: { id: $id }, data: { status: $status }) {
      id
    }
  }
}