query DashboardQuery {
  labs {
    mentors {
      id
      name
      email
      status
      maxWeeks
      manager {
        username
        picture(transform: { width: 32, height: 32, fit: CROP })
        name
      }
      projects {
        status
        maxStudents
        track
      }
    }
  }
}
