#import "../../../../components/Dashboard/MentorProfile.gql"
#import "../../../../components/Dashboard/ProjectEditor.gql"
#import "../../../../components/Dashboard/MentorManagerDetails.gql"
#import "../../../../components/Dashboard/TagPicker.gql"
query MentorPageQuery ($id: String!) {
  labs {
    mentor (where: { id: $id }) {
      name
      ...MentorProfile
      ...MentorManagerDetails
      projects {
        ...ProjectEditor
      }
    }
    tags {
      ...TagPicker
    }
  }
}
