mutation AddNoteMutation($student: String!, $caution: Float!, $note: String!, $supportTicketType: LabsSupportTicketType) {
  labs {
    addNote(student: { id: $student }, caution: $caution, note: $note, supportTicketType: $supportTicketType) {
      id
    }
  }
}