query DashboardStudents {
  labs {
    mentors(where: { inStatus: ACCEPTED }) {
      id
      name
      maxWeeks
      email
      managerUsername
      profile
      projects {
        id
        status
        track
        students {
          id
          name
          partnerCode
          profile
          status
          track
          weeks
          email
          tagTrainingSubmissions {
            url
            tag {
              mentorDisplayName
            }
          }
        }
      }
    }
  }
}
