#import "../../../../components/Dashboard/Match.gql"
query StudentDashboardQuery {
  labs {
    projectPreferences {
      project {
        id
      }
    }
    event {
      id
      startsAt
      name
    }
    resources {
      id
      name
      link
    }
    surveys {
      id
      name
      occurrences {
        id
        dueAt
        surveyResponses {
          authorStudentId
        }
      }
    }
    student {
      id
      status
      track
      weeks
      projects {
        id
        ...Match
        mentors {
          name
          email
          profile
        }
      }
    }
  }
}
