#import "../../../../components/Dashboard/Match.gql"
query StudentDashboardQuery {
  labs {
    projectPreferences {
      project {
        id
      }
    }
    student {
      id
      status
      track
      projects {
        id
        ...Match
        mentors {
          name
          email
          profile
        }
      }
    }
  }
}
