query OfferAcceptStatus {
  labs {
    student {
      id
      givenName
      surname
      status
      weeks
      minHours
      hasValidAdmissionOffer
      event { name startsAt certificationStatements }
    }
  }
}

mutation AcceptOffer ($timeManagementPlan: LabsJSONObject!, $timezone: String!) {
  labs {
    acceptStudentOffer(timeManagementPlan: $timeManagementPlan, timezone: $timezone) {
      id
    }
  }
}
