query OfferAcceptStatus {
  labs {
    student {
      id
      givenName
      status
      weeks
      minHours
      hasValidAdmissionOffer
    }
  }
}

mutation AcceptOffer {
  labs {
    acceptStudentOffer {
      id
    }
  }
}
