mutation CreateSupportTicketMutation(
  $projectId: String!,
  $type: LabsSupportTicketType!,
  $description: String,
  $preventingProgress: Boolean
) {
  labs {
    createSupportTicket(projectId: $projectId, type: $type, description: $description, preventingProgress: $preventingProgress)
  }
}

query ProjectsQuery {
  labs {
    student {
      projects { id mentors { name } students { name } }
    }
  }
}