#import "../../../../components/Dashboard/ProjectEditor.gql"
#import "../../../../components/Dashboard/MentorManagerDetails.gql"
#import "../../../../components/Dashboard/TagPicker.gql"
query DashboardQuery {
  labs {
    mentor {
      name
      givenName
      surname
      ...MentorManagerDetails
      projects {
        ...ProjectEditor
      }
    }
    surveys {
      id
      name
      occurrences {
        id
        dueAt
        surveyResponses {
          authorMentorId
        }
      }
    }
    tags {
      ...TagPicker
    }
  }
}
