#import "../../../../components/Dashboard/ProjectEditor.gql"
#import "../../../../components/Dashboard/MentorProfile.gql"
#import "../../../../components/Dashboard/MentorManagerDetails.gql"
#import "../../../../components/Dashboard/TagPicker.gql"
query DashboardQuery {
  labs {
    event {
      name
      startsAt
    }
    students {
      name
      weeks
    }
    resources {
      name
      link
    }
    mentor {
      id
      name
      givenName
      surname
      ...MentorManagerDetails
      ...MentorProfile
      projects {
        ...ProjectEditor
      }
    }
    surveys {
      id
      name
      occurrences {
        id
        dueAt
        surveyResponses {
          authorMentorId
        }
      }
    }
    tags {
      ...TagPicker
    }
  }
}
