#import "../components/Index/Explainer.gql"
#import "../components/Index/Header.gql"
#import "../components/Index/PastProjects.gql"
#import "../components/Index/Testimonials.gql"
#import "../components/Index/ProjectSlider.gql"
#import "../components/Index/TAs.gql"
#import "../providers/ProgramDates.gql"

query IndexQuery {
  ...IndexExplainer
  ...IndexHeader
  ...IndexPastProjects
  ...IndexTestimonials
  ...ProjectSlider
  ...ProgramDates
  ...TAs

  labs {
    studentAppsOpenEvents: events(where:{ public:true, state: ACCEPTING_STUDENT_APPLICATIONS }) {
      id
    }
  }
}
