query EligibilityQuery ($username: String!) {
  account {
    getUser (where: { username: $username }) {
      roles {
        id
      }
    }
  }

  labs {
    myEvents: events(where: { mine: true } ) {
      id
      name
      iAmStudent
      iAmMentor
    }
    events {
      id
      name
      iAmStudent
      iAmMentor
    }
  }
}