query MatchingPrefs ($take: Float!, $skip: Float!) {
  labs {
   students(where:{inStatus:ACCEPTED, withProjects:false}, take: $take, skip: $skip) {
      username
      track
      weeks
      id
      timezone
      timeManagementPlan
      projectPreferences {
        ranking
        project {
          id
          track
          mentors {
            givenName
            surname
            maxWeeks
          }
        }
      }
    }
  }
}
