#import "../../../../components/Dashboard/Match.gql"

query PartnerStudentsAbout {
  labs {
    students {
      id
      name
      email
      timeManagementPlan
      minHours
      timezone
      status
      hasProjectPreferences
      token
      projects {
        id
        ...Match
        mentors {
          name
        }
        tags {
          id
          mentorDisplayName
          trainingLink
        }
      }
      tagTrainingSubmissions {
        url
        tag {
          id
        }
      }
      surveyResponsesAbout {
        surveyOccurence {
          id
          survey { id name personType }
          dueAt
        }
        authorMentor { id name }
        authorStudent { id name }
        response
        caution
      }
    }
  }
}

mutation AssociatePartnerCodeMutation ($where: LabsIdOrUsernameOrEmailInput!) {
  labs {
    associatePartnerCode(where: $where) {
      id
      givenName
      surname
    }
  }
}