#import "../../../../components/Dashboard/Match.gql"

query PartnerStudentsAbout {
  labs {
    students {
      id
      name
      email
      timeManagementPlan
      minHours
      timezone
      status
      hasProjectPreferences
      projects {
        id
        ...Match
        mentors {
          name
        }
        tags {
          id
          mentorDisplayName
          trainingLink
        }
      }
      tagTrainingSubmissions {
        url
        tag {
          id
        }
      }
      notes {
        id
        createdAt
        username
        note
        caution
      }
      surveyResponsesAbout {
        id
        surveyOccurence {
          id
          survey {
            id
            name
            personType
            selfDisplay
            peerDisplay
            menteeDisplay
            mentorDisplay
            projectDisplay
          }
          dueAt
        }
        authorMentor { id name }
        authorStudent { id name }
        mentor { id }
        student { id }
        response
        caution
      }
    }
  }
}

mutation AssociatePartnerCodeMutation ($where: LabsIdOrUsernameOrEmailInput!) {
  labs {
    associatePartnerCode(where: $where) {
      id
      givenName
      surname
    }
  }
}