query PartnerStudentsAbout {
  labs {
    students {
      id
      name
      timeManagementPlan
      minHours
      timezone
      surveyResponsesAbout {
        surveyOccurence {
          id
          survey { id name personType }
          dueAt
        }
        authorMentor { id name }
        authorStudent { id name }
        response
        caution
      }
    }
  }
}
