#import "./Dashboard/TagPicker.gql"

mutation ApplyMutation(
  $givenName: String!,
  $surname: String!,
  $email: String!,
  $timezone: String,
  $track: LabsTrack!,
  $minHours: Int!,
  $partnerCode: String,
  $tags: [String!],
  $profile: LabsJSONObject,
  $resume: Upload,
) {
  labs {
    applyStudent(data:{
      givenName: $givenName
      surname: $surname
      email: $email
      track: $track
      minHours: $minHours
      partnerCode: $partnerCode
      tags: $tags
      profile: $profile
      timezone: $timezone
      resume: $resume
    }) {
      id
    }
  }
}

query ApplyFormQuery {
  labs {
    event {
      studentApplicationsStartAt
      studentApplicationsEndAt
      studentApplicationSchema
      studentApplicationUi
    }
    applicationId
    tags {
      ...TagPicker
    }
  }
}