query LabsEventInfo {
    labs {
        event {
            id
            name
            startsAt
        }
        otherEventTokens {
            event { id name startsAt }
            token
        }
    }
}