query AutocompleteQuery ($q: String!, $students: Boolean, $mentors: Boolean, $projects: Boolean, $status: [LabsStudentStatus!]) {
  labs {
    autocomplete(types: { students: $students, mentors: $mentors, projects: $projects }, status: $status, q: $q) {
      type
      name
      id
    }
  }
}