fragment MentorProfile on LabsMentor {
  id
  givenName
  surname
  username
  email
  profile
  status
  managerUsername
  maxWeeks
  timezone
}

mutation EditMentor (
  $id: String!,
  $givenName: String!,
  $surname: String!,
  $email: String!,
  $profile: LabsJSONObject!,
  $status: LabsMentorStatus!,
  $managerUsername: String!,
  $maxWeeks: Int!,
  $timezone: String,
) {
  labs {
    editMentor(
      where: { id: $id },
      data: {
        givenName: $givenName,
        surname: $surname,
        email: $email,
        profile: $profile,
        status: $status,
        managerUsername: $managerUsername,
        maxWeeks: $maxWeeks,
        timezone: $timezone,
      },
    ) {
      ...MentorProfile
    }
  }
}

mutation EditMentorLimited (
  $givenName: String!,
  $surname: String!,
  $email: String!,
  $profile: LabsJSONObject!,
  $timezone: String,
) {
  labs {
    editMentor(
      data: {
        givenName: $givenName,
        surname: $surname,
        email: $email,
        profile: $profile,
        timezone: $timezone,
      },
    ) {
      ...MentorProfile
    }
  }
}
