fragment ProjectEditor on LabsProject {
  id
  description
  deliverables
  track
  maxStudents
  status
  affinePartnerId
  affinePartner {
    partnerCode
  }
  mentors {
    id
    name
  }
  tags {
    id
  }
  students {
    name
    email
    tagTrainingSubmissions {
      url
      tag {
        mentorDisplayName
      }
    }
  }
}

mutation EditProject(
  $id: String!,
  $data: LabsProjectEditInput!,
) {
  labs {
    editProject(project: $id, data: $data) {
      ...ProjectEditor
    }
  }
}
