fragment ProjectEditor on LabsProject {
  id
  description
  deliverables
  track
  maxStudents
  status
  mentors {
    id
    name
  }
  tags {
    id
  }
}

mutation EditProjectLimited(
  $id: String!,
  $description: String,
  $deliverables: String,
  $tags: [String!],
  $status: LabsProjectStatus
) {
  labs {
    editProject(project: $id, data: {
      description: $description,
      deliverables: $deliverables,
      tags: $tags,
      status: $status
    }) {
      ...ProjectEditor
    }
  }
}

mutation EditProject(
  $id: String!,
  $description: String,
  $deliverables: String,
  $status: LabsProjectStatus!,
  $track: LabsTrack!,
  $maxStudents: Int!,
  $tags: [String!],
) {
  labs {
    editProject(project: $id, data: {
      description: $description,
      deliverables: $deliverables,
      status: $status,
      track: $track,
      maxStudents: $maxStudents,
      tags: $tags,
    }) {
      ...ProjectEditor
    }
  }
}
