#import "../../../../components/Dashboard/StudentHeader.gql"
#import "../../../../components/Dashboard/StudentApplication.gql"

query StudentNeedingRating {
  labs {
    nextStudentNeedingRating {
      ...StudentApplication
      ...StudentHeader
    }
  }
}

query StudentNeedingRatingInTrack ($track: LabsTrack!) {
  labs {
    nextStudentNeedingRating(track: $track) {
      ...StudentApplication
      ...StudentHeader
    }
  }
}

mutation SubmitRating($id: String!, $rating: Int!, $track: LabsTrack!) {
  labs {
    submitStudentRating(where: { id: $id }, rating: $rating, track: $track)
  }
}
