fragment ProfilePageInformation on LabsStudent {
  id
  givenName
  surname
  track
  minHours
  tags {
    mentorDisplayName
  }
  profile
}

query StudentNeedingRating {
  labs {
    nextStudentNeedingRating {
      ...ProfilePageInformation
    }
  }
}

query StudentNeedingRatingInTrack ($track: LabsTrack!) {
  labs {
    nextStudentNeedingRating(track: $track) {
      ...ProfilePageInformation
    }
  }
}

mutation SubmitRating($id: String!, $rating: Int!, $track: LabsTrack!) {
  labs {
    submitStudentRating(where: { id: $id }, rating: $rating, track: $track)
  }
}
